# Generated by Django 5.0.6 on 2024-07-10 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='prodect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='sub_prodct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_price', models.IntegerField()),
                ('p_img', models.ImageField(upload_to='')),
                ('p_model', models.CharField(max_length=50)),
                ('p_ram', models.CharField(max_length=30)),
                ('p_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.prodect')),
            ],
        ),
    ]
