# Generated by Django 5.0.6 on 2024-07-11 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_doctors_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctors',
            name='logo',
        ),
    ]
