# Generated by Django 5.0.6 on 2024-07-15 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_doctors_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='doctors',
        ),
    ]
