# Generated by Django 5.0.6 on 2024-07-16 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_doctors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointments',
            old_name='patientadd',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='appointments',
            old_name='patientname',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='appointments',
            old_name='weight',
            new_name='note',
        ),
        migrations.RenameField(
            model_name='appointments',
            old_name='patientnumber',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='date',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='time',
        ),
    ]
