# Generated by Django 5.0.6 on 2024-07-18 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_rename_patientadd_appointments_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('dname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.doctors')),
                ('pname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.appointments')),
            ],
        ),
    ]
