# Generated by Django 5.0.7 on 2024-08-01 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_remove_time_pname_remove_time_date_remove_time_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=10)),
                ('phone', models.BigIntegerField()),
                ('dob', models.DateField()),
                ('address', models.CharField(max_length=100)),
                ('note', models.CharField(max_length=100)),
                ('dname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.doctors')),
            ],
        ),
    ]
