# Generated by Django 5.0.7 on 2024-08-01 19:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_remove_appointments_dname_delete_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('dname', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.doctors')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.login')),
            ],
        ),
    ]
