# Generated by Django 5.0.7 on 2024-08-01 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='time',
        ),
    ]
