# Generated by Django 5.0.7 on 2024-08-01 22:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='dname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.appointments'),
        ),
        migrations.DeleteModel(
            name='doctors',
        ),
    ]
