# Generated by Django 5.0.7 on 2024-08-03 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_remove_time_pname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='dname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.doctors'),
        ),
    ]
