# Generated by Django 5.0.7 on 2024-08-06 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_remove_time_dname'),
    ]

    operations = [
        migrations.DeleteModel(
            name='time',
        ),
    ]
