# Generated by Django 5.0.7 on 2024-08-06 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0029_alter_time_dname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='time',
            name='dname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.doctors'),
        ),
    ]
