# Generated by Django 5.0.7 on 2024-08-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0033_appointments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
