# Generated by Django 5.0.7 on 2024-08-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0034_alter_doctors_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctors',
            name='logo',
            field=models.ImageField(upload_to='static/images/doctor'),
        ),
    ]
