# Generated by Django 5.0.7 on 2024-08-06 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0035_alter_doctors_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='appointments',
        ),
    ]
