# Generated by Django 5.0.7 on 2024-08-07 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0038_remove_appointments_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='address',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='age',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='name',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='note',
        ),
        migrations.RemoveField(
            model_name='appointments',
            name='phone',
        ),
    ]
