# Generated by Django 5.0.7 on 2024-08-07 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0039_remove_appointments_address_remove_appointments_age_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='appointments',
        ),
    ]
