# Generated by Django 5.0.6 on 2024-05-29 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studinfo',
            old_name='addreas',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='studinfo',
            old_name='deb',
            new_name='dob',
        ),
    ]
