# Generated by Django 5.0.6 on 2024-06-15 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='login',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
