# Generated by Django 5.0.6 on 2024-06-15 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_login_phone'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='login',
            new_name='logi',
        ),
    ]
