# Generated by Django 5.0.6 on 2024-07-14 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='img',
            name='time',
            field=models.TimeField(auto_now=True),
        ),
    ]
